WebApplication5/Controllers/registerController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Security;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApplication5.Models;

namespace WebApplication5.Controllers
{
    public class registerController : Controller
    {
        // GET: register
        [HttpGet]
        public ActionResult register()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
    }
}

WebApplication5/Views/register/Login.cshtml
@*@{
        ViewBag.Title = "Login";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    @section Scripts {
        @Scripts.Render("~/bundles/app")
    }
    <div class="row">
        <div class="col-sm-4">
            <form data-bind="submit: callApi">
                <h3>Invoke API</h3>
                <div class="form-group">
                    <label>User</label>
                    <input class="form-control" type="text" readonly data-bind="value: user" />
                </div>
                <div class="form-group">
                    <label>Result</label>
                    <input class="form-control" type="text" readonly data-bind="value: result" />
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-default">Call API</button>
                </div>
                <div class="form-group error-messages" data-bind="foreach: errors">
                    <p data-bind="text: $data" />
                </div>
            </form>
        </div>
        <div class="col-sm-4">
            <form data-bind="submit: register">
                <h3>Register</h3>
                <div class="form-group">
                    <label>Email</label>
                    <input class="form-control" type="text" data-bind="value: registerEmail" />
                </div>
                <div class="form-group">
                    <label>Password</label>
                    <input class="form-control" type="password" data-bind="value: registerPassword" />
                </div>
                <div class="form-group">
                    <label>Confirm Password</label>
                    <input class="form-control" type="password" data-bind="value: registerPassword2" />
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-default">Register</button>
                </div>
            </form>
        </div>
        <div class="col-sm-4">
            <h3>Log In</h3>
            <form data-bind="submit: login">
                <div class="form-group">
                    <label>Email</label>
                    <input class="form-control" type="text" data-bind="value: loginEmail" />
                </div>
                <div class="form-group">
                    <label>Password</label>
                    <input class="form-control" type="password" data-bind="value: loginPassword" />
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-default">Log In</button>
                    <button data-bind="click: logout" class="btn btn-default">Log Out</button>
                </div>
            </form>
        </div>
    </div>*@



@{
    ViewBag.Title = "ورود";
    Layout = "~/Views/Shared/_login.cshtml";
}

@using CaptchaMvc.HtmlHelpers
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="../../Content/AdminLTE-RTL-master/bootstrap/css/bootstrap-rtl.css">
    <link rel="stylesheet" href="../../Content/AdminLTE-RTL-master/dist/css/AdminLTE-rtl.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="../../Content/AdminLTE-RTL-master/plugins/iCheck/square/blue.css">
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/app")

    }
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
</head>


<body class="hold-transition register-page" id="test">


    <form data-bind="submit: callApi">
        <div class="form-group error-messages" data-bind="foreach: errors">
            <p data-bind="text: $data" />
        </div>
    </form>



    <div class="register-box">

        <div class="register-box-body">

            <p class="login-box-msg" style="color:dodgerblue">ورود به سایت</p>

            <form data-bind="submit: login" >
                <div class="form-group has-feedback">
                    <label>ایمیل</label>
                    <input class="form-control" type="text" data-bind="value: loginEmail" />
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <label>رمز عبور</label>
                    <input class="form-control" type="password" data-bind="value: loginPassword" />
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>

                @*<div class="form-group">
                    @Html.Captcha(5)
                    <input type="hidden" data-bind="" value=""/>
                    </div>*@
                    <div class="form-group">

                        <div class="col-md-5"><button type="submit" class="btn btn-info col-md-10">ورود</button></div>

                        @Html.ActionLink("ثبث نام در سایت", "register", null, new { @class = "btn btn-warning" })
                    </div>
</form>
            <p>
            </p>
            @* Enable this once you have account confirmation enabled for password reset functionality*@
            <p>
            </p>
        </div>
        <!-- /.form-box -->
    </div>
    <script src="~/Scripts/jquery-1.10.2.intellisense.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>


</body>

</html>

WebApplication5/Views/register/register.cshtml
@{
    ViewBag.Title = "ثبت نام";
    Layout = "~/Views/Shared/_login.cshtml";
}

<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="../../Content/AdminLTE-RTL-master/bootstrap/css/bootstrap-rtl.css">
    <link rel="stylesheet" href="../../Content/AdminLTE-RTL-master/dist/css/AdminLTE-rtl.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="../../Content/AdminLTE-RTL-master/plugins/iCheck/square/blue.css">
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/app")

    }
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
</head>


<body class="hold-transition register-page" id="test">

    <form data-bind="submit: callApi">
        <div class="form-group error-messages" data-bind="foreach: errors">
            <p data-bind="text: $data" />
        </div>
    </form>

    <div class="register-box">

        <div class="register-box-body">

            <p class="login-box-msg" style="color:dodgerblue">ثبت نام در سایت</p>

            <form data-bind="submit: register">
                <div class="form-group has-feedback">
                    <label>ایمیل</label>
                    <input class="form-control" type="text" data-bind="value: registerEmail" />
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <label>رمز عبور</label>
                    <input class="form-control" type="password" data-bind="value: registerPassword" />
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <label>تکرار رمز عبور</label>
                    <input class="form-control" type="password" data-bind="value: registerPassword2" />
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success">ثبت نام</button>
                </div>
            </form>

            <p>
                @Html.ActionLink("ورود به سایت", "Login", null, new { @class = "btn btn-info" })
            </p>
            @* Enable this once you have account confirmation enabled for password reset functionality*@
            <p>
            </p>
        </div>
        <!-- /.form-box -->
    </div>
    <script src="~/Scripts/jquery-1.10.2.intellisense.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate-vsdoc.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>


</body>

</html>